[package]
name = "exchange-rs"
version = "0.1.0"
authors = ["carl"]

[workspace]
members = [
    "matcher"
]

[dependencies]
matcher = { path = "./matcher" }
rocket = "0.3.11"
rocket_contrib = "0.3.11"
rocket_codegen = "0.3.11"